services:
  - type: web
    name: fritha-ecommerce-backend
    env: node
    plan: free
    buildCommand: "npm install --legacy-peer-deps && npm run build"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000 

